apiVersion: networking.vkcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: my-frontend-subnet
spec:
  forProvider:
    name: my-frontend-subnet
    networkId: 6112d71e-418b-424f-96b9-4a8854fd7cbf
    cidr: 10.10.1.0/24
    enableDhcp: true
  providerConfigRef:
    name: default
---
apiVersion: networking.vkcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: my-backend-subnet
spec:
  forProvider:
    name: my-backend-subnet
    networkId: 6112d71e-418b-424f-96b9-4a8854fd7cbf
    cidr: 10.10.2.0/24
    enableDhcp: false
  providerConfigRef:
    name: default
