apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: vk-cloud-credentials
type: Opaque
stringData:
  creds: |
    {
      "username": "glinisty.ad@gmail.com",
      "password": "Underbam111999!",
      "domain": "users",
      "projectId": "9db77e367336474aad6fe589ca6729e3",
      "authUrl": "https://infra.mail.ru:35357",
      "neutronUrl": "https://infra.mail.ru:9696"
    }
---
apiVersion: vkcloud.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: vk-cloud-credentials
      key: creds
